#!/bin/bash

# if [ ! -n "$1" ] || [ "$#" -ne 1 ]; then
#     echo "Usage: ./install_as <projdir> <appname> <versionnum> <vbox_job.xml>" <
#     exit
# fi

set -e

PROJDIR=$1
APPNAME=$2
VER=$3
VBOXJOB_IN=$4

APPROOT=$PROJDIR/apps/$APPNAME/$VER
mkdir -p $APPROOT 

for PLATFORM in "x86_64-pc-linux-gnu" "windows_x86_64" "x86_64-apple-darwin"; do
    APPFOLDER=$APPROOT/${PLATFORM}__vbox64_mt
    cp -Lrf apps/boinc2docker/1.0/${PLATFORM}__vbox64_mt $APPROOT 
    VBOXJOB_OUT=$APPFOLDER/${APPNAME}_${VER}_vbox_job.xml 
    if [ -z $VBOXJOB_IN ]; then VBOXJOB_IN=apps/boinc2docker/1.0/example/vbox_job.xml; fi
    cp $VBOXJOB_IN $VBOXJOB_OUT
    sed -i "s/%vbox_job%/$(basename $VBOXJOB_OUT)/g" $APPFOLDER/version.xml
done

for type in "in" "out"; do 
    cp -f templates/boinc2docker_$type $PROJDIR/templates/${APPNAME}_$type
done
