#!/bin/sh

#
# the "-v /root/shared:/root/shared" sets up 
# /root/shared (inside the boot2docker VM) == /root/shared (inside the docker container)
# both of these are then just a mount of slot/#/shared (on the host)
# 
# "/root/shared/params" is the logical name of whichever input param file we select
# 
docker run -v /root/shared:/root/shared busybox echo "I'm running inside Docker!"


# any regular linux commands can also be run as long as 
# they work correctly inside the boot2docker VM
echo "Docker app finished."
