#!/bin/sh

#
# the "-v /root/shared:/root/shared" sets up 
# /root/shared (inside the boot2docker VM) == /root/shared (inside the docker container)
# both of these are then just a mount of slot/#/shared (on the host)
# 
# "/root/shared/params" is the logical name of whichever input param file we select
# 
docker run -v /root/shared:/root/shared busybox echo /root/shared/params


# any regular linux commands can also be run as long as 
# it works correctly inside the boot2docker VM
echo "Done"
